### PR TITLE
both aqara switches 

### PR DESCRIPTION
**Pull request by Levynger**
both aqara switches now works in domoticz, 
both uses Selector switch.

### CODE REVIEW

**Comment by corbinmunce** [comment]
please update this code so I can merge:

std::string rotate = root2["rotate"].asString();
						if (rotate != "") {
							//convert to int
							int amount = atoi(rotate.c_str());
							if (amount > 0) {
								level = 90;
							}
							else {
								level = 100;
							}
							on = true;
						}
						//if (rotate == "") {
							std::string battery = root2["battery"].asString();
							if (battery != "") {
								m_XiaomiGateway->InsertUpdateVoltage(sid.c_str(), name, atoi(battery.c_str()));
							}
							else {
								m_XiaomiGateway->InsertUpdateSwitch(sid.c_str(), name, on, type, level);
							}
						//}

**Comment by corbinmunce** [comment]
see https://github.com/corbinmunce/domoticz/blob/master/hardware/XiaomiGateway.cpp

**Comment by Levynger** [comment]
thanks, i will update it soon, although my code only deals with the report, and write commands stil needs to be added, as Im trying to figure out how, and where to get the "On/Off" event from domoticz to send the relevant command to the switch, 

im new to the domoticz....

**Comment by corbinmunce** [comment]
Do you need Domoticz to send the state to the switch?  The Xiaomi wireless switch and cube do not need it - if you look at the WriteToHardware function it will ignore sSwitchTypeSelector switches.

**Comment by deennoo** [comment]
230v switch can be drive by the app as explain on api.
86ctlr neutral and neutral2 are 2 ways devices

https://github.com/louisZL/lumi-gateway-local-api/blob/master/86ctrl_neutral1.md

And 
https://github.com/louisZL/lumi-gateway-local-api/blob/master/86ctrl_neutral2.md

**Comment by corbinmunce** [comment]
can you use packet sender to test these commands?  It doesn't use the encrypted key like other devices:

{"cmd":"write","model":" ctrl_neutral2","sid":"112316","short_id":4343,"data":"{\"channel_0\":\"on\"}" }

**Comment by Levynger** [comment]
Nothing seems to happen..
capture

**Comment by corbinmunce** [comment]
try putting the back slashes after data:

"data":"{\" channel_1\":\"on\"}"

**Comment by Levynger** [comment]
something like that ?
also fixed to use my SID and short_id..

{"cmd":"write","model":"ctrl_neutral2","sid":"158d0001190076","short_id":27074,"data":"{\"channel_0\":\"on\"}"}

still doesnt seems to work..

**Comment by Levynger** [comment]
`{"cmd":"report","model":"ctrl_neutral2","sid":"158d0001190076","short_id":27074,"data":"{\"channel_0\":\"on\"}"}`

**Comment by corbinmunce** [comment]
do you know if anyone else has got these write commands working?  Not everything in these docs is correct.

**Comment by corbinmunce** [comment]
also try changing the model to "86sw2"

**Comment by Levynger** [comment]
Nope, doesnt work with 86sw2 either.. 
tries also with another UDP sender, as the Packetsender messed up due to the / characters. 
still doesnt work.

i will explore if someone else was able to get it to work.

**Comment by Levynger** [comment]
apperently, i was using the wrong IP...
you must use key
{"cmd":"write_ack","sid":"158d0001190076","data":"{\\"error\\":\\"No key\\"}"}

**Comment by corbinmunce** [comment]
That indicates it will work then.  Can you update your code to match the changes in https://github.com/corbinmunce/domoticz/blob/master/hardware/XiaomiGateway.cpp

Otherwise I can implement your changes myself but you won't get accreditation

**Comment by Levynger** [comment]
done, check new pull request

**Pull request closed without merging**
